apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-phpfpm
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.phpfpmService.type }}
  ports:
  - port: {{ .Values.phpfpmService.phpfpmPort }}
    targetPort: {{ .Values.phpfpmService.phpfpmPort }}
    protocol: TCP
    name: {{ .Values.phpfpmService.name }}
  selector:
    app: {{ template "fullname" . }}-phpfpm
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.redisService.type }}
  ports:
  - port: {{ .Values.redisService.redisPort }}
    targetPort: {{ .Values.redisService.redisPort }}
    protocol: TCP
    name: {{ .Values.redisService.name }}
  selector:
    app: {{ template "fullname" . }}-redis
