apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireping.fullname" . }}-fpm
  labels:
    {{- include "fireping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000 
      targetPort: 9000 
      protocol: TCP
      name: fpm 
  selector:
    {{- include "fireping.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fireping.fullname" . }}-nginx
  labels:
    {{- include "fireping.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080 
      targetPort: 8080 
      protocol: TCP
      name: http 
  selector:
    {{- include "fireping.selectorLabels" . | nindent 4 }}